root: true

env:
  browser: true,
  mocha: true

extends:
  - xo-react/space
  - xo-space/esnext

parser: babel-eslint

settings:
  react:
    version: detect

rules:
  curly:
    - error
    - multi-or-nest
    - consistent
  keyword-spacing:
    - error
    - overrides:
        catch:
          after: false
        for:
          after: false
        if:
          after: false
        switch:
          after: false
        while:
          after: false
  new-cap:
    - error
    - capIsNew: false
  no-return-assign:
    - error
    - except-parens
  no-unused-expressions:
    - error
    - allowTernary: true
  object-curly-spacing:
    - error
    - always
  one-var: off
  quotes:
    - error
    - single
  space-before-function-paren:
    - error
    - never

  # react
  react/jsx-closing-bracket-location: off
  react/jsx-first-prop-new-line: off
  react/jsx-handler-names:
    - error
    - eventHandlerPrefix: on
  react/jsx-max-props-per-line: off
  react/jsx-no-bind:
    - error
    - allowArrowFunctions: true
  react/prop-types:
    - error
    - skipUndeclared: true
