#!/bin/sh
cat /root/index.html | envsubst > index.html
cat /root/default.conf | DOLLAR='$' envsubst > /etc/nginx/conf.d/default.conf

# web flag
if [ -n "$WEB_FLAG_PATH" ]; then
  mkdir -p $(dirname "$WEB_FLAG_PATH")
  echo "$WEB_FLAG_VALUE" > "$WEB_FLAG_PATH"
fi

if [ -n "$KITSUNE_WEB_CERT" ]; then
  echo "$KITSUNE_WEB_CERT" | base64 -d > "/etc/nginx/$KITSUNE_WEB_SERVER_NAME.crt"
fi

if [ -n "$KITSUNE_WEB_KEY" ]; then
  echo "$KITSUNE_WEB_KEY" | base64 -d > "/etc/nginx/$KITSUNE_WEB_SERVER_NAME.key"
fi

nginx -g 'daemon off;'
